### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by tututututututu** [asyalas/react-native-smart-refresh-flatlist#1]
一直显示正在加载中...
demo跑不起来
IOS 跑不起来

**Comment by tututututututu** [comment]
android 需要添加ACCESS_NETWORK_STATE 权限
IOS 红屏No component found for view with name “ARTShap”

**Comment by tututututututu** [comment]
一点小建议:
将这个组件做得更纯粹,不需要将fetch放进去,网络问题应该是外面调用的时候的事情,这个组件只需要刷新,加载更多,添加数据,刷新数据,刷新完成,加载完成几个回调就好了

**Comment by asyalas** [comment]
抱歉，最近有点忙，一直没上github，非常感谢能给我提问。
1、一直显示正在加载中的话 你可以换一个自己的接口来试试，这个接口有点不稳定
2、android 需要添加ACCESS_NETWORK_STATE 权限  这个是因为我用了NetInfo，安卓需要配置，已经加到readme里面了
3、IOS 红屏No component found for view with name “ARTShap” 这个是因为我用了ART，在ios里面需要配置Libraries，现在已经被我注释掉了
4、非常感谢你的小建议，我当初的想法是尽量减少在父组件的逻辑操作，最简单的就是配置一个fetch就可以了，所有的逻辑都给你封装好了，你的建议也是个很好的方向，以后有机会可以试着重构下
